if(NOT DEFINED EXECUTABLE OR NOT DEFINED USAGE_EXECUTABLE OR NOT DEFINED FIXTURE_DIR OR NOT DEFINED PEAKS_FILE OR NOT DEFINED OUTPUT_DIR)
  message(FATAL_ERROR "Missing integration test arguments")
endif()
file(REMOVE_RECURSE "${OUTPUT_DIR}")
file(MAKE_DIRECTORY "${OUTPUT_DIR}")
execute_process(COMMAND "${EXECUTABLE}" "${FIXTURE_DIR}" 2 3
  WORKING_DIRECTORY "${OUTPUT_DIR}" RESULT_VARIABLE result
  OUTPUT_VARIABLE output ERROR_VARIABLE error)
if(NOT result EQUAL 0)
  message(FATAL_ERROR "autoencoder failed (${result})\nstdout:\n${output}\nstderr:\n${error}")
endif()
if(NOT output MATCHES "Learned 3 embeddings with latent dimension 2")
  message(FATAL_ERROR "evaluation did not produce expected embeddings\n${output}")
endif()
foreach(artifact autoencoder_model.pt norm.txt)
  if(NOT EXISTS "${OUTPUT_DIR}/${artifact}")
    message(FATAL_ERROR "${artifact} was not created")
  endif()
endforeach()
file(READ "${OUTPUT_DIR}/norm.txt" normalization)
string(REGEX MATCHALL "[-+0-9.eE]+" normalization_values "${normalization}")
list(LENGTH normalization_values normalization_count)
if(NOT normalization_count EQUAL 12)
  message(FATAL_ERROR "norm.txt should contain 12 values, got ${normalization_count}")
endif()
execute_process(COMMAND "${USAGE_EXECUTABLE}" "${OUTPUT_DIR}/autoencoder_model.pt"
  "${OUTPUT_DIR}/norm.txt" "${FIXTURE_DIR}" "${PEAKS_FILE}" A
  WORKING_DIRECTORY "${OUTPUT_DIR}" RESULT_VARIABLE usage_result
  OUTPUT_VARIABLE usage_output ERROR_VARIABLE usage_error)
if(NOT usage_result EQUAL 0)
  message(FATAL_ERROR "usage_cpp failed (${usage_result})\n${usage_output}\n${usage_error}")
endif()
if(NOT usage_output MATCHES "Predicted sequence:")
  message(FATAL_ERROR "usage_cpp produced no prediction\n${usage_output}")
endif()
